project:
  type: book
  output-dir: docs

book:
  title: "soubie_chronicles"
  author: "Santiago Soubie"
  date: "20/1/2026"
  chapters:
    - index.qmd
    - class1.qmd
    - class2.qmd
    - class3.qmd
    - class4.qmd
    - class5.qmd
    - class6.qmd
    - class7.qmd
    - class8.qmd


bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

