# Preface {.unnumbered}

Hola! I’m Santiago. I’m a Political Scientist, Urban Economist, and Data Scientist.

I’m particularly interested in the intersection between urbanism and computational science, and how the use of data, geospatial tools, and open government practices can support evidence-based decision-making to build more sustainable and livable cities.

I have worked as an Open Data Director at Argentina’s Secretariat of Innovation, Science and Technology and at the Undersecretariat of Tourism. I am also a member of IDERA (Argentina’s Spatial Data Infrastructure) and a Graduate Teaching Assistant at Torcuato Di Tella University.

Nowadays, I am studying Urban Spatial Science at the Center for Advanced Spatial Analysis at UCL. There, I am learning about remote sensing and earth observation techniques among many things. This informal diary has the intent to record the main ideas and knowledge that I extract from each class.

Currently, I am studying Urban Spatial Science at the Centre for Advanced Spatial Analysis (CASA), UCL. There, I am learning about remote sensing and Earth observation techniques, among other topics. This informal diary aims to document the main ideas and knowledge that I gain from each class.

I truly believe that it is worthwhile to explore Remote Sensing in greater depth if one is interested in urbanism and geospatial data. Data is everywhere; however, it remains difficult to access high-quality open data to work. Remote sensing, although initially challenging to grasp, can provide us with unique tools to bridge the information gap, as it enables large-scale, systematic, and continuous data collection across territories where traditional data sources are limited, outdated, or inaccessible.

```{r, echo=FALSE}
# xaringanExtra::embed_xaringan(url = "https://ssoubie.github.io/practice_2/#1",
#                               ratio = "16:9")
```

